apiVersion: v1
kind: Service
metadata:
  name: apiservice
  labels: 
    group: backend
spec:
  type: ClusterIP
  selector:
    app: apiservice
  ports:
  - name: http
    port: {{.Values.api.service.port}}
    targetPort: {{.Values.api.image.targetPort}}

