apiVersion: v1
kind: Service
metadata:
  name: webfrontend
  labels: 
    group: frontend
spec:
  type: ClusterIP
  selector:
    app: webfrontend
  ports:
  - name: http
    port: {{.Values.web.service.port}}
    targetPort: {{.Values.web.image.targetPort}}
