
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfrontend
  labels:
    app: webfrontend
    group: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webfrontend
  template:
    metadata:
      labels:
        app: webfrontend
    spec:
      containers:
        - name: webfrontend
          image: {{.Values.web.image.repository}}:{{.Values.web.image.tag}}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.web.config.name }}
          ports:
            - containerPort: {{.Values.web.image.targetPort}}
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"