api:
  config:
      name: api-config
      data:
        - key: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
          value: "true"
        - key: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
          value: "true"
        - key: ASPNETCORE_URLS
          value: http://+:8080 
  image:
    repository: apiservice
    tag: "latest"
    targetPort: 8080
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080

web:
  config:
      name: web-config
      data:
        - key: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
          value: "true"
        - key: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
          value: "true"
        - key: services__apiservice__0
          value: http://apiservice:8080
        - key: services__apiservice__1
          value: https://apiservice:8443   
        - key: ASPNETCORE_URLS
          value: http://+:8080               
  image:
    repository: webfrontend
    tag: "latest"
    targetPort: 8080
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080

ingress:
  name: ingress-service
  replicaCount: 1
  className: "nginx"
  annotations: {  }
  hosts:
    - host: cel.local.internal
      paths: 
        - path: /
          pathType: Prefix
          backend:
            serviceName: webfrontend
            servicePort: 8080